In [149]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [150]:
data = pd.read_csv('/Users/ilmasheriff/Desktop/Studentdata.csv',header = 0, low_memory=False)
data.head()

Student Number2  Ending YRTR  Start YRTR  Ending Term Ending Term Type  \
0              1.0      20143.0     20043.0    Fall 2013             Fall   
1              2.0      20173.0     20173.0    Fall 2016             Fall   
2              3.0      20143.0     20125.0    Fall 2013             Fall   
3              4.0      20145.0     20133.0  Spring 2014           Spring   
4              5.0      20145.0     20023.0  Spring 2014           Spring   

         Admission Category  Male  Female  Gender  Student of Color Value  \
0    Undergraduate Transfer   0.0     1.0  Female                     0.0   
1  Undergraduate First-Time   0.0     1.0  Female                     0.0   
2  Undergraduate First-Time   1.0     0.0    Male                     0.0   
3  Undergraduate First-Time   0.0     1.0  Female                     0.0   
4  Undergraduate First-Time   0.0     1.0  Female                     0.0   

   ... Transfer Time in Years  Transfer Time Category  \
0  ...                    NaN                     NaN   
1  ...                    NaN                     NaN   
2  ...                    NaN                     NaN   
3  ...                    NaN                     NaN   
4  ...                    NaN                     NaN   

  Transfer Instituion Type Transfer Instituion Name Transfer Instituion State  \
0                      NaN                      NaN                       NaN   
1                      NaN                      NaN                       NaN   
2                      NaN                      NaN                       NaN   
3                      NaN                      NaN                       NaN   
4                      NaN                      NaN                       NaN   

   Transfer Instituion In/Out State Transfer Instituion Public/Private  \
0                               NaN                                NaN   
1                               NaN                                NaN   
2                               NaN                                NaN   
3                               NaN                                NaN   
4                               NaN                                NaN   

   Transfer ZIP Transfer Region  Transfer = Home Region Value  
0           NaN         Unknown                           0.0  
1           NaN         Unknown                           0.0  
2           NaN         Unknown                           0.0  
3           NaN         Unknown                           0.0  
4           NaN         Unknown                           0.0  

[5 rows x 112 columns]

In [161]:
# data.shape
data.dtypes

Student Number2                       float64
Ending YRTR                           float64
Start YRTR                            float64
Ending Term                            object
Ending Term Type                       object
                                       ...   
Transfer Instituion In/Out State       object
Transfer Instituion Public/Private     object
Transfer ZIP                          float64
Transfer Region                        object
Transfer = Home Region Value          float64
Length: 112, dtype: object

In [153]:
class MultiColumnLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,X,y=None):
        return self # not relevant here

    def transform(self,X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self,X,y=None):
        return self.fit(X,y).transform(X)

In [164]:
data = MultiColumnLabelEncoder(columns = data.columns).fit_transform(data)

data = pd.DataFrame(data)
data.head()

Student Number2  Ending YRTR  Start YRTR  Ending Term  Ending Term Type  \
0                0            0           8            0                 0   
1                1            6          34            3                 0   
2                2            0          25            0                 0   
3                3            1          26            5                 1   
4                4            1           4            5                 1   

   Admission Category  Male  Female  Gender  Student of Color Value  ...  \
0                   1     0       1       0                       0  ...   
1                   0     0       1       0                       0  ...   
2                   0     1       0       1                       0  ...   
3                   0     0       1       0                       0  ...   
4                   0     0       1       0                       0  ...   

   Transfer Time in Years  Transfer Time Category  Transfer Instituion Type  \
0                       1                       0                         1   
1                       1                       0                         1   
2                       1                       0                         1   
3                       1                       0                         1   
4                       1                       0                         1   

   Transfer Instituion Name  Transfer Instituion State  \
0                       391                         21   
1                       391                         21   
2                       391                         21   
3                       391                         21   
4                       391                         21   

   Transfer Instituion In/Out State  Transfer Instituion Public/Private  \
0                                 0                                   1   
1                                 0                                   1   
2                                 0                                   1   
3                                 0                                   1   
4                                 0                                   1   

   Transfer ZIP  Transfer Region  Transfer = Home Region Value  
0           245                5                             0  
1           245                5                             0  
2           245                5                             0  
3           245                5                             0  
4           245                5                             0  

[5 rows x 112 columns]

In [165]:
data["Student Outcome"].nunique()

3

In [159]:
data.isna().sum().sort_values(ascending = False)

Transfer = Home Region Value            0
Transfer Region                         0
Ending Term New or Continuing Status    0
Ending Term Cumulated GPA               0
Ending Term Enrollment Status           0
                                       ..
Start Term DFW Grades                   0
Start Term DFW Category                 0
Start Term DF Grades                    0
Start Term W Grades                     0
Student Number2                         0
Length: 112, dtype: int64

In [158]:
for column in data.columns:
    data[column].fillna(data[column].mode()[0], inplace=True)

In [66]:
x_df = pd.DataFrame(data, columns = [
                   'Starting Term Cumulative GPA', 
    'First Generation MN Value', 'First Generation FED Value','Pell Eligible Value',
    'First Generation or Pell Eligible Value',
    'Starting Term Academic Standing','Ending Term Academic Standing',
    'Starting to Ending Term Academic Standing Change',
    'Starting to Ending Term CRHR Completion Change',
    'Starting to Ending Term GPA Change','Last Term Quadrant'
    
    
                  'Ending Term Cumulated GPA', 
                  'Ending Term Credits', 
            'Starting Term CRHR Completion', 
            'Ending Term CRHR Completion', 
                  'Pre-Enrollment Credits',
                   'Ending Term Unmet Need',
                   'Declared Programs',
                   'Academic Suspension Hold', 
                   'Academic Warning Hold', 
            'Academic Probation Hold', 
                   'Academic Hold', 
            'Unpaid Balance Hold', 
                  'Past Due Balance Hold', 
                  'Immunization Hold',
            'Admissions Hold', 'Conduct Hold', 
            'International Insurance Hold', 
            'Veteran Benefits Hold', 'Athletic Hold Hold', 'Non-Academic Hold', 
            'Active Hold', 'Multiple Holds','Start Term DFW Grades', 
            'Start Term DF Grades', 'Start Term W Grades', 'Cumulative DFW Grades', 
            'Cumulative DF Grades', 'Cumulative W Grades', 'Total Term Count', 
'Cumulated Debt', 'Average Debt Per Term', 
                   'Lost Tuition Revenue',
'Organization Count', 'Organization Y/N', 'Organization Value',
                  'Stop Out Terms', 'Stop Out Years','Student Outcome'
])


In [156]:
x_df.isna().sum().sort_values(ascending = False)

Student Outcome                  0
Academic Warning Hold            0
Conduct Hold                     0
Admissions Hold                  0
Immunization Hold                0
Past Due Balance Hold            0
Unpaid Balance Hold              0
Academic Hold                    0
Academic Probation Hold          0
Academic Suspension Hold         0
Veteran Benefits Hold            0
Declared Programs                0
Ending Term Unmet Need           0
Pre-Enrollment Credits           0
Ending Term CRHR Completion      0
Starting Term CRHR Completion    0
Ending Term Credits              0
Ending Term Cumulated GPA        0
International Insurance Hold     0
Athletic Hold Hold               0
Stop Out Years                   0
Total Term Count                 0
Stop Out Terms                   0
Organization Value               0
Organization Y/N                 0
Organization Count               0
Lost Tuition Revenue             0
Average Debt Per Term            0
Cumulated Debt      

In [68]:
for column in x_df.columns:
    x_df[column].fillna(x_df[column].mode()[0], inplace=True)

In [69]:
X = x_df.iloc[:, :-1].values 
y = x_df.iloc[:, -1].values

In [70]:
print(X)

[[4.0 3.78 40.0 ... 0.0 9.0 4.5]
 [2.0 2.0 12.0 ... 0.0 0.0 0.0]
 [3.45 3.45 171.33 ... 0.0 2.0 1.0]
 ...
 [1.33 1.33 47.0 ... 1.0 0.0 0.0]
 [1.92 1.92 9.0 ... 0.0 0.0 0.0]
 [4.0 4.0 120.0 ... 0.0 0.0 0.0]]


In [71]:
# x_df = x_df.replace('', np.nan)
# x_df = x_df.dropna()
x_df.fillna(0, inplace=True)


cleanup_nums_y = { "Student Outcome": {"Transferred Out": 3, "Graduated": 2, "Dropped Out": 1},
                   "Organization Y/N":     {"Yes": 2, "No": 1}
                 }
x_df.replace(cleanup_nums_y, inplace=True)
x_df.head()

Starting Term Cumulative GPA  Ending Term Cumulated GPA  \
0                          4.00                       3.78   
1                          2.00                       2.00   
2                          3.45                       3.45   
3                          4.00                       4.00   
4                          2.80                       3.33   

   Ending Term Credits  Starting Term CRHR Completion  \
0                40.00                           1.00   
1                12.00                           1.00   
2               171.33                           0.94   
3                58.00                           1.00   
4               111.00                           1.00   

   Ending Term CRHR Completion  Pre-Enrollment Credits  \
0                         0.87                     8.0   
1                         1.00                     0.0   
2                         0.94                     0.0   
3                         1.00                     0.0   
4                         1.00                     0.0   

   Ending Term Unmet Need  Declared Programs  Academic Suspension Hold  \
0                     0.0                2.0                       0.0   
1                     0.0                1.0                       0.0   
2                     0.0                1.0                       0.0   
3                     0.0                3.0                       0.0   
4                     0.0                2.0                       0.0   

   Academic Warning Hold  ...  Total Term Count  Cumulated Debt  \
0                    0.0  ...              12.0             0.0   
1                    0.0  ...               1.0             0.0   
2                    0.0  ...               2.0             0.0   
3                    0.0  ...               5.0             0.0   
4                    0.0  ...              17.0         10586.0   

   Average Debt Per Term  Lost Tuition Revenue  Organization Count  \
0               0.000000               25070.0                 1.0   
1               0.000000               28060.0                 1.0   
2               0.000000               30820.0                 1.0   
3               0.000000               17480.0                 1.0   
4             622.705882               30820.0                 1.0   

   Organization Y/N  Organization Value  Stop Out Terms  Stop Out Years  \
0                 1                 0.0             9.0             4.5   
1                 1                 0.0             0.0             0.0   
2                 1                 0.0             2.0             1.0   
3                 1                 0.0             0.0             0.0   
4                 1                 0.0            13.0             6.5   

   Student Outcome  
0                1  
1                1  
2                1  
3                1  
4                2  

[5 rows x 39 columns]

In [72]:
x_df.shape

(21014, 39)

In [61]:
x_df["Student Outcome"].nunique()

3

In [62]:
x_df.isna().sum().sort_values(ascending = False)

Student Outcome                  0
Academic Warning Hold            0
Conduct Hold                     0
Admissions Hold                  0
Immunization Hold                0
Past Due Balance Hold            0
Unpaid Balance Hold              0
Academic Hold                    0
Academic Probation Hold          0
Academic Suspension Hold         0
Veteran Benefits Hold            0
Declared Programs                0
Ending Term Unmet Need           0
Pre-Enrollment Credits           0
Ending Term CRHR Completion      0
Starting Term CRHR Completion    0
Ending Term Credits              0
Ending Term Cumulated GPA        0
International Insurance Hold     0
Athletic Hold Hold               0
Stop Out Years                   0
Total Term Count                 0
Stop Out Terms                   0
Organization Value               0
Organization Y/N                 0
Organization Count               0
Lost Tuition Revenue             0
Average Debt Per Term            0
Cumulated Debt      

In [63]:
x_df.to_csv('/Users/ilmasheriff/Desktop/cleaned_dataset.csv',index=False)